### ISSUE TITLE
Crew transfer stuck

### ISSUE THREAD

**Issue by tivec** [PapaJoesSoup/ShipManifest#11]
I have the 4.2.1 version installed, and tried to do a crew transfer from a PPD-24 Itinerant Service Container (From the NearFutureSpacecraft mod). Now I've gone several orbits around Kerbin, and according to the crew view in Ship Manifest, the scientist is still moving.

http://i.imgur.com/ooyvkLu.png

There's only one error in the debug console:

```
Error: Transfer State: Start...

Error:  in RealModeCrewXfer (repeating error).  Error:  Object reference not set to an instance of an object 

  at ShipManifest.SMAddon.RealModeCrewXfer () [0x00000] in <filename unknown>:0 
```

Is there anything I can do to get rid of tthe window now? Since I can't close it it will always be visible when I have the ship active.

**Comment by tivec** [comment]
Update: This might have been caused because of CKAN not properly updating to the newest version. Upon removing the mod and reinstalling it, transfers seem to work again.

**Comment by PapaJoesSoup** [comment]
I wonder if CKAN is actually removing the old and installing the new... Even if that were true, I would think it should still work... My revised config file should be more robust now and tolerant of changes...

Anyway, glad that re-installing fixed it.
