### ISSUE TITLE
Hidden Resources

### ISSUE THREAD

**Issue by CovertJaguar** [PapaJoesSoup/ShipManifest#15]
Some resources, such as USI Life Support Replacement Parts, are designated as "isVisible=false" and are not normally user interactable. Ship Manifest should probably respect this flag, at least optionally.

**Comment by PapaJoesSoup** [comment]
Thanks for this!   I agree and will include in the upcoming release.   quick fix.

**Comment by PapaJoesSoup** [comment]
Incorporated in 5.0.0.1
