### ISSUE TITLE
Bug: Science info tooltip disappears off the bottom of the screen when list is scrolled

### ISSUE THREAD

**Issue by jd284** [PapaJoesSoup/ShipManifest#18]
I have a vessel with ~150 science reports. For the first 5 reports, the tooltip is in the right place, but as I scroll down the tooltip doesn't follow this, so the more I scroll, the further down the screen the tooltip appears, and eventually it appears off the bottom and makes it impossible to see the info on the science report.

To reproduce:
- Add dozens of science reports to a vessel
- Open manifest, select "Science" transfer, then select the part with science in the transfer window
- Press "+" to expand the science detail
- Scroll down the list, hover mouse over an entry
- The tooltip appears in the wrong place, too far down or even off the bottom of the screen

**Comment by PapaJoesSoup** [comment]
Fixed in 5.0.0.1.   I refactored the tool tip engine.   I had misunderstood Unity and screen vs Gui positioning.
