### ISSUE TITLE
Feature request: Transfer window option to select science reports already processed by the science lab

### ISSUE THREAD

**Issue by jd284** [PapaJoesSoup/ShipManifest#19]
When my science reports have been processed in the Mobile Processing Lab (or other science lab), I would like to retrieve them and recover them at KSC, or transfer them to a lab on a different body for additional processing.
It is currently very tedious to manually go through the manifest list and transfer only those reports that have already been processed. Basically I have to:
- Review the science reports
- Advance through the science window to find the reports which were already processed
- Hunt through the manifest transfer window to find the corresponding report in the list by comparing the tooltip info with the science window
- Transfer the one report
- Repeat this process another dozen times or more

It would be nice to have a special option to select and/or transfer all science reports that were already processed in the lab.
(Since KSP is buggy with more than one lab on a vessel it should be safe to just check the first one, if 1.1 fixes this maybe the selection should be limited to items that haven't been processed in all labs.)

**Comment by PapaJoesSoup** [comment]
Incorporated contents of pull request.   Will be in upcoming maint. release.  Thanks!
