### ISSUE TITLE
KIS Inventories are not swapped when swapping crewmembers

### ISSUE THREAD

**Issue by PapaJoesSoup** [PapaJoesSoup/ShipManifest#21]
when swapping crewmembers (target part is full), inventories are not alsow swapped.  In addition, when moving a crewmember to another seat within the same part, the inventory also does not move.

Reported by by: jofwu

Forum Link:  http://forum.kerbalspaceprogram.com/index.php?/topic/56643-105-ship-manifest-crew-science-resources-v-5010-14-mar-16/&do=findComment&comment=2435359

**Comment by mwerle** [comment]
Additionally, anytime when moving a crew members to a new part, the KIS inventory is not moved with the crew member. (KSP1.3.1.1, SM 5.2.0.0, various other mods; removing SM and trying again resulted in the Kerbal moving along with their KIS inventories)

Attached my modlist. Most are probably not required to reproduce; but you will need Nehemiah-Inc complete, the Corvus pod, and of course SM and their dependencies to reproduce. The vessel is Orbit 2.3, and moving Jebedia from the Mk1 pod leaves the inventory in the Mk1 pod, after Jeb has moved.

[installed-default.zip](https://github.com/PapaJoesSoup/ShipManifest/files/1397555/installed-default.zip)
[persistent (2017_10_18_18_16_21).zip](https://github.com/PapaJoesSoup/ShipManifest/files/1397554/persistent.2017_10_18_18_16_21.zip)

**Comment by mwerle** [comment]
Fixed this, it was probably broken in 7a45d2060cd8bc7efdca833e0d807c743bd5cd8d when the Source- and TargetAction callbacks were no longer being set up.
