### ISSUE TITLE
Override Stock Transfers in 1.1 - Portraits glitch.

### ISSUE THREAD

**Issue by JPLRepo** [PapaJoesSoup/ShipManifest#27]
In KSP 1.1 Override Stock transfers:-
The stock transfer appears to work and you see the kerbal's portraits change.
Then SM un-does the stock transfer, their portrait disappears, it counts down the SM transfer time and then completes the SM transfer.

**Comment by PapaJoesSoup** [comment]
Corrected with 5.1.0.0
