### ISSUE TITLE
Bumping Spacedock versioning

### ISSUE THREAD

**Issue by NathanKell** [PapaJoesSoup/ShipManifest#28]
Heya, wondered if you'd mind setting version_min to 1.1.2 and max to 1.1.3 so CKAN can grab this for 1.1.3 since per thread (and my experience) it works ok.

Same deal for CLS.

If that doesn't work (if spacedock only supports unitary version), mind if we make a netkan override?

**Comment by PapaJoesSoup** [comment]
Ill see if i can set it on the release.  
I'll be releasing updates for both within hours.  I had some debugging to do


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by NathanKell** [comment]
oh, that's even better :)

**Comment by PapaJoesSoup** [comment]
I updated SpaceDock for both anyway :)

**Comment by NathanKell** [comment]
<3
