### ISSUE TITLE
NullReferenceException on crew transfer or boarding a vessel

### ISSUE THREAD

**Issue by darchambault** [PapaJoesSoup/ShipManifest#34]
Running the latest version of ShipManifest (5.1.3.1).

I have a station in orbit of the Mun consisting of a few different vessels docked together. On that station, I am unable to transfer crew between locations through the SM crew transfer system. Also, trying to board the station from EVA crashes the game.

Here is what I see from the logs...

For the crew transfer:

> [LOG 23:53:02.387] [ShipManifest] - Error:  Transfer State:  Off...
> [LOG 23:53:02.387] [ShipManifest] - Error:   in CrewTransferProcess (repeating error).  Error:  Object reference not set to an instance of an object 
> 
>   at ShipManifest.Process.TransferCrew.CrewTransferProcess () [0x00000] in <filename unknown>:0 
> [LOG 23:53:02.461] [ShipManifest] - Error:  Error in:  SMAddon.UpdateSMcontroller.  System.NullReferenceException: Object reference not set to an instance of an object
>   at ShipManifest.Modules.ModDockedVessel.get_LaunchId () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMVessel.UpdateDockedVessels () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMVessel.RefreshLists () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMAddon.UpdateSMcontroller (.Vessel newVessel) [0x00000] in <filename unknown>:0 
> [LOG 23:53:02.463] [ShipManifest] - Error:  Error in:  SMAddon.UpdateSMcontroller.  System.NullReferenceException: Object reference not set to an instance of an object
>   at ShipManifest.Modules.ModDockedVessel.get_LaunchId () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMVessel.UpdateDockedVessels () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMVessel.RefreshLists () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMAddon.UpdateSMcontroller (.Vessel newVessel) [0x00000] in <filename unknown>:0 
> [LOG 23:53:02.464] [KerbNet Controller] Scanning Vessel [Mun Station Alpha]... Found [1] KerbNet Parts
> [LOG 23:53:02.465] AudioMuffler: VesselGeometryCache rebuild time = 0
> [LOG 23:53:02.480] AudioMuffler: VesselSoundsCache rebuild time = 2
> [LOG 23:53:02.482] [BetterBurnTime] Vessel changed to Mun Station Alpha
> [LOG 23:53:02.483] [ShipManifest] - Error:  Error in:  SMAddon.UpdateSMcontroller.  System.NullReferenceException: Object reference not set to an instance of an object
>   at ShipManifest.Modules.ModDockedVessel.get_LaunchId () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMVessel.UpdateDockedVessels () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMVessel.RefreshLists () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMAddon.UpdateSMcontroller (.Vessel newVessel) [0x00000] in <filename unknown>:0 
> [LOG 23:53:02.484] [ShipManifest] - Error:  Error in:  SMAddon.UpdateSMcontroller.  System.NullReferenceException: Object reference not set to an instance of an object
>   at ShipManifest.Modules.ModDockedVessel.get_LaunchId () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMVessel.UpdateDockedVessels () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMVessel.RefreshLists () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMAddon.UpdateSMcontroller (.Vessel newVessel) [0x00000] in <filename unknown>:0

And when attempting to board from EVA I have this in the logs:

> [LOG 23:52:01.967] [ShipManifest] - Error:  Error in:  SMAddon.UpdateSMcontroller.  System.NullReferenceException: Object reference not set to an instance of an object
>   at ShipManifest.Modules.ModDockedVessel.get_LaunchId () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMVessel.UpdateDockedVessels () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMVessel.RefreshLists () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMAddon.UpdateSMcontroller (.Vessel newVessel) [0x00000] in <filename unknown>:0 
> [LOG 23:52:01.969] [ShipManifest] - Error:  Error in:  SMAddon.UpdateSMcontroller.  System.NullReferenceException: Object reference not set to an instance of an object
>   at ShipManifest.Modules.ModDockedVessel.get_LaunchId () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMVessel.UpdateDockedVessels () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMVessel.RefreshLists () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMAddon.UpdateSMcontroller (.Vessel newVessel) [0x00000] in <filename unknown>:0 
> [LOG 23:52:01.970] [KerbNet Controller] Scanning Vessel [Mun Station Alpha]... Found [1] KerbNet Parts
> [LOG 23:52:01.970] AudioMuffler: VesselGeometryCache rebuild time = 0
> [LOG 23:52:01.985] AudioMuffler: VesselSoundsCache rebuild time = 1
> [LOG 23:52:01.986] [BetterBurnTime] Vessel changed to Mun Station Alpha
> [LOG 23:52:01.987] [ShipManifest] - Error:  Error in:  SMAddon.UpdateSMcontroller.  System.NullReferenceException: Object reference not set to an instance of an object
>   at ShipManifest.Modules.ModDockedVessel.get_LaunchId () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMVessel.UpdateDockedVessels () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMVessel.RefreshLists () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMAddon.UpdateSMcontroller (.Vessel newVessel) [0x00000] in <filename unknown>:0 
> [LOG 23:52:01.989] [ShipManifest] - Error:  Error in:  SMAddon.UpdateSMcontroller.  System.NullReferenceException: Object reference not set to an instance of an object
>   at ShipManifest.Modules.ModDockedVessel.get_LaunchId () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMVessel.UpdateDockedVessels () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMVessel.RefreshLists () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMAddon.UpdateSMcontroller (.Vessel newVessel) [0x00000] in <filename unknown>:0 
> [LOG 23:52:01.990] AudioMuffler: VesselGeometryCache rebuild time = 0
> [LOG 23:52:02.004] AudioMuffler: VesselSoundsCache rebuild time = 1
> [LOG 23:52:02.005] FF: EventObserver:: OnVesselChange Mun Station Alpha
> [LOG 23:52:02.007] [ShipManifest] - Error:  Error in:  SMAddon.UpdateSMcontroller.  System.NullReferenceException: Object reference not set to an instance of an object
>   at ShipManifest.Modules.ModDockedVessel.get_LaunchId () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMVessel.UpdateDockedVessels () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMVessel.RefreshLists () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMAddon.UpdateSMcontroller (.Vessel newVessel) [0x00000] in <filename unknown>:0 
> [LOG 23:52:02.008] [KerbNet Controller] Scanning Vessel [Mun Station Alpha]... Found [1] KerbNet Parts
> [LOG 23:52:02.009] AudioMuffler: VesselGeometryCache rebuild time = 0
> [LOG 23:52:02.023] AudioMuffler: VesselSoundsCache rebuild time = 1
> [LOG 23:52:02.024] [ShipManifest] - Error:  Error in:  SMAddon.UpdateSMcontroller.  System.NullReferenceException: Object reference not set to an instance of an object
>   at ShipManifest.Modules.ModDockedVessel.get_LaunchId () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMVessel.UpdateDockedVessels () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMVessel.RefreshLists () [0x00000] in <filename unknown>:0 
>   at ShipManifest.SMAddon.UpdateSMcontroller (.Vessel newVessel) [0x00000] in <filename unknown>:0

**Comment by PapaJoesSoup** [comment]
Corrected in release 5.1.3.3
