### ISSUE TITLE
Can't respawn kerbal. NullReference

### ISSUE THREAD

**Issue by megastupidmonkey** [PapaJoesSoup/ShipManifest#35]
When I try to respawn a dead kerbal it does nothing and I get this error in the debug console:

[LOG 14:49:51.125] [ShipManifest] - Error:   in RosterListViewer.  Error:  Object reference not set to an instance of an object 

  at ShipManifest.Windows.WindowRoster.DisplayRosterListViewer () [0x00000] in <filename unknown>:0

**Comment by PapaJoesSoup** [comment]
Found and fixed bug.  Will be corrected in version 5.1.3.2  release
