### ISSUE TITLE
Total amount of resources is not preserved during transfer

### ISSUE THREAD

**Issue by Vladimir-csp** [PapaJoesSoup/ShipManifest#36]
Here is an example of 12% increase of LF+OX after transfer between two ships (multiple different tanks on both). http://imgur.com/a/5UfzN

**Comment by PapaJoesSoup** [comment]
Is the vessel transfer mode enabled?  Or, are you simply selecting multiple parts in the source and destination?

**Comment by Vladimir-csp** [comment]
Both ways.

**Comment by PapaJoesSoup** [comment]
Thanks.  Looking at that section of code now.

**Comment by PapaJoesSoup** [comment]
Think I have this licked.  I've not been able to reproduce since my fixes.  We will see.  Fix will be included in 5.1.4.0

**Comment by Vladimir-csp** [comment]
Unfortunately, I'm still seeing this with 5.2.0.
Transfering from one Jumbo to 4xFL-T400, I get extra fuel. Transfering back reduces to amount a bit less than before starting point.
