### ISSUE TITLE
Tooltips don't respect "Hide UI"

### ISSUE THREAD

**Issue by cake-pie** [PapaJoesSoup/ShipManifest#38]
http://forum.kerbalspaceprogram.com/index.php?/topic/56643-122-ship-manifest-crew-science-resources-v-5133-29-jan-17/&do=findComment&comment=3048741

**Comment by PapaJoesSoup** [comment]
I have added a condition check for showing hiding tooltips.  should behave exactly the same as the SM UI
Will be included in the next release.

**Comment by PapaJoesSoup** [comment]
Fix will be in version 5.1.4.0
