### ISSUE TITLE
Mark as compatible with KSP 1.3.1

### ISSUE THREAD

**Issue by cmheisel** [PapaJoesSoup/ShipManifest#46]
I've been playing with KSP 1.3.1 and ShipManifest 5.2.0.0 without any issues for month plus now.

I'm not sure where in the code base that's managed or how it informs CKAN, but I'll gladly work on a patch if you can give me a pointer in the right direction?

Thanks!

**Comment by PapaJoesSoup** [comment]
Thanks!  I've been in China on vacation and just returned.  I'll make the necessary changes.

**Comment by cmheisel** [comment]
@PapaJoesSoup Awesome, I hope it was a great trip!

**Comment by PapaJoesSoup** [comment]
Updated version.info file to reflect new version and KSP compatibility
