### ISSUE TITLE
Solar panel control+detection w/ Kopernicus

### ISSUE THREAD

**Issue by StewGoin** [PapaJoesSoup/ShipManifest#47]
I added SM to an existing game and couldn't get it to see my solar panels, etc... didn't seen anything obvious so I stripped out mods and did the one-by-one.

No issues with base game + SM, but with with Kopernicus Planetary System Modifier 2:release-1.3.1-3 the solar panels never appear in the SM UI for control. Antennas did still work, just not solar panels.

**Comment by arivaldh** [comment]
I'll implement it on my Fork, and I'll make pull request to main mod.

**Comment by arivaldh** [comment]
https://github.com/arivaldh/ShipManifest/commit/370d7927afb56809d5bc8d4501abfb1244d14460

**Comment by PapaJoesSoup** [comment]
Merged PR.
