### ISSUE TITLE
Overcapacity

### ISSUE THREAD

**Issue by DecPascal** [PapaJoesSoup/ShipManifest#8]
On pressing Xfer for any material, (I have seen it on water or monopropellant), from a full tank to a not full tank, it happens that full tank is overfull (for example, 1501/1500) .Then, you cannot perform any transfer of this material in the station. Transfer amount cannot be edited, and setting bar cannot be moved.

**Comment by PapaJoesSoup** [comment]
This has been corrected with release 0.90.0_4.0.2
